apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: life-support-systems
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
  namespace: fleet-default
spec:
  selector:
    matchLabels:
      supports: life-support-systems
