apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: life-support-workloads
  annotations:
    {}
    #  key: string
  labels:
    {}
    #  key: string
  namespace: fleet-default
spec:
  branch: main
  correctDrift:
    enabled: false
#    force: boolean
#    keepFailHistory: boolean
  insecureSkipTLSVerify: false
  paths:
    - /fleet/observability-rodeo/challenge-01
#    - string
  repo: https://github.com/hierynomus/rodeo-demo-apps
  targets:
    - clusterGroup: life-support-systems
